    - &${_ORG_NAME}
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: ${ORG_MSP_NAME}

        # ID to load the MSP definition as
        ID: ${ORG_MSP_NAME}

        MSPDir: crypto-config/peerOrganizations/${ORG_NAME}.example.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: ${ANCHOR_PEER_NAME}.${ORG_NAME}.example.com
              Port: 7051

