
    OrgsChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Capabilities:
              <<: *ApplicationCapabilities
            Organizations:
